### ISSUE TITLE
Self-Paced Web Accessibility Course: Use of detail summary elements

### ISSUE THREAD

**Issue by shawnthompson** [bati-itao/bati-itao.github.io#1097]
I would strongly suggest when using the `details` elements, to use the `open="open"` by default.

This will allow users to use the browsers find feature and not exclude any text found inside the `details` element.

This will also allow users who use an immersive reader to read the text and not have to interrupt their reading to expand the `summary` and break their concentration. 

This is has been a concern in the W3C Cognitive task force with the W3.org website. 

It's actually a best practices we would like to bring into action on the [Digital Accessibility Toolkit](https://a11y.canada.ca) website.

**Comment by Jefferydo** [comment]
Thanks for the feedback. 
Such a change isn't without drawbacks. We use the details elements almost exclusively to hold long blocks of code. Opening them all explodes the height of already-long pages, making them cluttered and unwieldy for sighted users scrolling, particularly on smaller screens.
We might be better off providing an "Expand all details" button on pages sporting them. The trick is locating it.

**Comment by Jefferydo** [comment]
We're implementing the buttons directly following the TOC, as per the W3C website's usage.

**Comment by shawnthompson** [comment]
Sorry I missed this reply. Thank you for adding the button. 

Another problem with the `details` element is you can't use the browsers find feature to find information on the page in a collapsed `details`. 

Some users might not know that they need to expand all the information before using the find option in the browser. 

This is one of the reason why [Making Content Usable for People with Cognitive and Learning Disabilities](https://www.w3.org/TR/coga-usable/) chose to not use the expand / collapse for their long document. Which we are revising to find other ways to present it because it is a huge document.

Is there a better way to layout these pages or create multiple pages? What about using something like the [Filter - Working examples - Web Experience Toolkit](https://wet-boew.github.io/wet-boew/demos/filter/filter-en.html)?
