### ISSUE TITLE
Accessibility Compliance Assessments on ICT Solutions - Number of Working Days

### ISSUE THREAD

**Issue by MaximPerry** [bati-itao/bati-itao.github.io#1357]
This [Service delivery standard](https://bati-itao.github.io/services/service-standards-en.html) page needs to be updated:

We have recently agreed to increased the **Number of Working Days** for "Accessibility Compliance Assessments on ICT Solutions" from 15 to 20. The page should reflect this information.

**Comment by OptimusTestPrime** [comment]
This has been changed.
