### ISSUE TITLE
Modifications to the page

### ISSUE THREAD

**Issue by LegaultJ** [bati-itao/bati-itao.github.io#1440]
Hi! 

One of our sign language interpretion service providers has asked us to change their business information on these following  pages. Can you submit my request to the person who takes care of updates?

https://bati-itao.github.io/resources/CART-services-Sign-Language-Interpreters-en.html
https://bati-itao.github.io/resources/CART-services-Sign-Language-Interpreters-fr.html

The modifications to be made are as follows:

•	Change any reference of “Sign Language Interpreting Associates Ottawa Inc. (SLIAO)” or “SLIAO” to “Asign”
•	Change email [asl.interpreting@sliao.ca](mailto:asl.interpreting@sliao.ca) to [hello@asign.ca](mailto:hello@asign.ca) 
•	Update hyperlinks to: [www.asign.ca](http://www.asign.ca/)

Thank you!

**Comment by OptimusTestPrime** [comment]
This has been fixed.
