### ISSUE TITLE
Team page: certification icon descriptions

### ISSUE THREAD

**Issue by shawnthompson** [bati-itao/bati-itao.github.io#160]
I would suggest putting a description on the [IT Accessibility Office (ITAO) Team](https://bati-itao.github.io/teams/svatic-ictaas/index-en.html) to say what the certifications icons mean and not just using hidden text for screen readers. Also adding a link to the certification text in the list.

![image](https://user-images.githubusercontent.com/2575266/127664201-f6a97012-343c-48e0-babd-787b29226d0b.png)

**Comment by fredymoko** [comment]
Thanks @shawnthompson. Issue has been resolved (PR # 385 and #389)
