### ISSUE TITLE
UPDATE to 2 documents on https://bati-itao.github.io/resources/accessible-documents-en.html and FR

### ISSUE THREAD

**Issue by AnneSimard** [bati-itao/bati-itao.github.io#167]
J’ai fait 2 changements à notre gabarit :
•	un ajout à la case A9 : documents interne versus externe; et 
•	une nouvelle case A11 : texte à interligne minimum de 1,5. 

les documents sont MSDocument_audit_report_EN & FR dans Sharepoint:
https://dialogue/grp/BU6206833/Compliance/Forms/Activity/docsethomepage.aspx?ID=604&FolderCTID=0x0120D5200099AB14C91413CE459519A777E2DDD91A00BE16300567CF3441AA4184985CC40AA1&List=9cd87e5e-9d47-4af2-9d86-1bbd8d60fec6&RootFolder=%2Fgrp%2FBU6206833%2FCompliance%2FMS%20Office%20Document%20Audit%20Reports

**Comment by fredymoko** [comment]
The update has been made. I also resolved (Item #4 was skipped on both pages).
