### ISSUE TITLE
move the scripts to the main repo

### ISSUE THREAD

**Issue by shawnthompson** [bati-itao/bati-itao.github.io#2]
We should move the [script folders](https://github.com/bati-itao/example/tree/master/scripts) from all the project repos to this main repo and reference them with an absolute URI.

Instead of `<script src="./scripts/refTop.min.js"></script>`we use `<script src="https://bati-itao.github.io/scripts/refTop.min.js"></script>`

**Comment by delphinegilbert** [comment]
issue is resolved
