### ISSUE TITLE
French landing page is missing EDSC in the title

### ISSUE THREAD

**Issue by shawnthompson** [bati-itao/bati-itao.github.io#4]
The blue title bar is mossing the department name in the title

https://bati-itao.github.io/index-fr.html

![image](https://user-images.githubusercontent.com/2575266/81179519-c196ff00-8f77-11ea-8b44-d250c7f683ab.png)

It should be this:

EDSC / Bureau de l'accessibilite des TI

**Comment by delphinegilbert** [comment]
issue is resolved
