### ISSUE TITLE
Problem with Fr&En on Documents accessibles /Accessible Documents

### ISSUE THREAD

**Issue by AnneSimard** [bati-itao/bati-itao.github.io#56]
Le site Microsoft dont on offre le lien affiche les étapes à suivre pour Office365, Office2019 et Office2016… et non pas seulement Office365
(extrait de Microsoft:
Ajouter un texte de remplacement aux éléments visuels dans Office 2016
…fin de l’extrait)

Je suggère que l’on **supprime**  (pour Microsoft Office 365).  Sinon, les gens seront induit en erreur et n’iront pas utiliser l’information!

Page GitHub en français :
[Documents accessibles - EDSC / Bureau de l’accessibilité des TI ](https://bati-itao.github.io/resources/accessible-documents-fr.html) 
•	[Vidéos de formation d’accessibilité](https://support.microsoft.com/fr-fr/office/vid%C3%A9os-de-formation-d-accessibilit%C3%A9-71572a1d-5656-4e01-8fce-53e35c3caaf4) 
ENLEVER: (pour Microsoft Office 365)

Page GitHub en Anglais:
[Accessible Documents - ESDC / IT Accessibility office] (https://bati-itao.github.io/resources/accessible-documents-en.html)
•	[Accessibility Video training](https://support.microsoft.com/en-us/office/accessibility-video-training-71572a1d-5656-4e01-8fce-53e35c3caaf4)
ENLEVER: (for Microsoft Office365)

**Comment by ericmoore123** [comment]
Fixed
