### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by AnneSimard** [bati-itao/bati-itao.github.io#89]
ENGLISH PAGE:
Microsoft Document Compliance Checklist - ESDC / IT Accessibility office (bati-itao.github.io)

Resources
Making files accessible 
OLD https://www.hhs.gov/web/section-508/making-files-accessible/index.html 
NEW https://www.hhs.gov/web/section-508/accessibility-checklists/index.html

FRENCH PAGE 
Making Files Accessible (English only).
OLD https://www.hhs.gov/web/section-508/making-files-accessible/index.html 
NEW https://www.hhs.gov/web/section-508/accessibility-checklists/index.html

**Comment by ericmoore123** [comment]
Fixed

**Find changes at:**
https://bati-itao.github.io/resources/ms-doc-compliance-checklist-en.html
https://bati-itao.github.io/resources/ms-doc-compliance-checklist-fr.html
